export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const RETRIEVE_EMPLOYEE = "RETRIEVE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";

export const DESTROY_SESSION = "DESTROY_SESSION";

export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR'